SilverLifestyle/Models/Post.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilverLifestyle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int PostId { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string PostText { get; set; }
        public string PosterId { get; set; }
        public string PostImage { get; set; }
    }
}

SilverLifestyle/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using SilverLifestyle.Models;

namespace SilverLifestyle.Controllers
{
    public class PostsController : Controller
    {
        private SilverEntityEntities db = new SilverEntityEntities();

        // GET: Posts
        public ActionResult Index()
        {
            return View(db.Posts.ToList());
        }

        // GET: Posts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // GET: Posts/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "PostId,PostDate,PostText,PostImage,PosterId")] Post post, HttpPostedFileBase postedFile)
        {
            ModelState.Clear();         // Required since returning a view in POST method 

            // Set the Poster ID to the User's ID in the authentication table
            post.PosterId = User.Identity.GetUserId();

            // Set the current date
            post.PostDate = DateTime.Now;

            // If a file has been attached
            if (postedFile != null)
            {
                // Define the path to the image
                var uniqueFileName = string.Format(@"{0}", Guid.NewGuid());
                post.PostImage = uniqueFileName;                            // Set current path to image in post
            }
            
            TryValidateModel(post);

            if (ModelState.IsValid)
            {
                // If a file has been attached
                if (postedFile != null)
                {
                    string serverPath = Server.MapPath("~/Uploads/");   // Define path to images on server
                    string fileExtension = System.IO.Path.GetExtension(postedFile.FileName);    // Define file extension
                    string filePath = post.PostImage + fileExtension;   // Define path to file with extension
                    post.PostImage = filePath;                          // Add image path with extension
                    postedFile.SaveAs(serverPath + post.PostImage);     // Save the file in specified server storage
                }
                
                db.Posts.Add(post);                     // Add the new post object to the db

                db.SaveChanges();                       // Save the changes to the db
                return RedirectToAction("Index");       // Send user back to index page (view)
            }

            return View(post);
        }

        // GET: Posts/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "PostId,PostDate,PostText,PostImage,PosterId")] Post post, HttpPostedFileBase editpostedFile)
        {
            var currentPost = db.Posts.FirstOrDefault(p => p.PostId == post.PostId);
            if (currentPost == null)
            {
                return HttpNotFound();
            }

            // If a file has been attached
            if (editpostedFile != null)
            {
                // Define the path to the image
                var uniqueFileName = string.Format(@"{0}", Guid.NewGuid());
                post.PostImage = uniqueFileName;                    // Set current path to image in post
                string serverPath = Server.MapPath("~/Uploads/");   // Define path to images on server
                string fileExtension = System.IO.Path.GetExtension(editpostedFile.FileName);    // Define file extension
                string filePath = post.PostImage + fileExtension;   // Define path to file with extension

                currentPost.PostImage = filePath;                   // Add image path with extension to update
                editpostedFile.SaveAs(serverPath + currentPost.PostImage);     // Save the file in specified server storage
            }

            if (ModelState.IsValid)
            {
                currentPost.PostText = post.PostText;
                currentPost.PostImage = post.PostImage;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(post);
        }

        // GET: Posts/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SilverLifestyle/Views/Posts/Create.cshtml
@model SilverLifestyle.Models.Post

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Posts", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PostText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostText, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Name">Select File</label> 
            <div class="col-md-10">
                <input type="file", name="postedFile" class="btn btn-default" accept="image/png, image/gif, image/jpeg" />
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SilverLifestyle/Views/Posts/Delete.cshtml
@model SilverLifestyle.Models.Post

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Post</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PostDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostText)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SilverLifestyle/Views/Posts/Details.cshtml
@model SilverLifestyle.Models.Post

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Post</h4>
    <hr />
    <dl class="dl-horizontal">
        @if (Model.PostDate != null)
        {
            <dt>
                <!--[at_symbol_here]Html.DisplayNameFor(model => model.PostDate)-->
                Post Date
            </dt>

            <dd>
            @Model.PostDate.Value.ToShortDateString()
            
            </dd>
        }

        <dt>
            Text
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostText)
        </dd>
        @if (Model.PostImage != null)
        {
            <dt>
                Image
            </dt>
            <dd>
                <img class="img-thumbnail" src='@Url.Content("~/Uploads/" + Model.PostImage)'
                     onerror="this.onerror=null" alt="">
            </dd>
        }
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PostId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SilverLifestyle/Views/Posts/Edit.cshtml
@model SilverLifestyle.Models.Post

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Post</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.PostId)

    <div class="form-group">
        @Html.LabelFor(model => model.PostText, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PostText, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PostText, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2" for="Name">Select File</label>
        <div class="col-md-10">
            <input type="file" , name="postedFile" class="btn btn-default" accept="image/png, image/gif, image/jpeg" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SilverLifestyle/Views/Posts/Index.cshtml
@model IEnumerable<SilverLifestyle.Models.Post>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="~/Content/customStyles.css">

<h2>Recent Posts</h2>

<p style="padding-bottom: 2rem">
    @Html.ActionLink("Tell Us Something New!", "Create")
</p>
<table class="table" style="table-layout:fixed; width:90%; margin: 0px auto;">
    @foreach (var item in Model.OrderByDescending(post => post.PostDate))
    {
        <tr>
            <td style="width:10%">
                @if (item.PostDate != null)
                {
                    <b>@item.PostDate.Value.ToShortDateString()</b>
                }
                else
                {
                    <b></b>
                }
            </td>
            <td>

                <p class="text" style="text-align:center; max-height:180px">@Html.DisplayFor(modelItem => item.PostText)</p>

                @if (item.PostImage != null)
                {
                    <img class="img-thumbnail center" style="max-width:60%; max-height:300px" src='@Url.Content("~/Uploads/" + item.PostImage)'
                         onerror="this.onerror=null" alt="">
                }
                else
                {
                    <img class="img-rounded" style="max-width:60%; max-height:300px" src='@Url.Content("~/Uploads/" + item.PostImage)'
                         onerror="this.onerror=null" alt="">
                }

            </td>
            @if (User.Identity.IsAuthenticated)
            {
                <td style="width:10%">
                    @Html.ActionLink("Edit", "Edit", new { id = item.PostId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.PostId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.PostId })
                </td>
            }
            else
            {
                <td>@Html.ActionLink("Details", "Details", new { id = item.PostId })</td>

            }
        </tr>
    }

</table>